/* CRIAR A DATABASE crud3 */
CREATE TABLE noticias (
  id_noticia INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(100) NOT NULL,
  texto VARCHAR(100) NOT NULL,
  data DATE NOT NULL,
  autor VARCHAR(100) NOT NULL
);